config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'customers#index'
  get '/customers/missing_email', to: 'customers#missing_email', as: 'missing_email_customers'
  get '/customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetized_customers'
  
  resources :customers
  
  # Defines the root path route ("/")
  # root "posts#index"
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord

    #Add validation
    validates :full_name, :phone_number, :notes, :image, presence: true

    has_one_attached :image
    
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "email_address", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
  end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def alphabetized
    @customers = Customer.order(:full_name)
  end
  def missing_email
    @customers = Customer.where("email_address IS NULL OR email_address = ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class= "container">
<h2 ><%= customer.full_name %></h2>
<div class="customer-info">
  <div class="customer-image">
    <% if customer.image.attached? %>
      <%= image_tag customer.image %>
    <% end %>
  </div>
  <div class="customer-details">
    <p><strong>Phone Number:</strong> <%= customer.phone_number %></p>
    <p><strong>Email Address:</strong> <%= customer.email_address %></p>
    <p><strong>Notes:</strong> <%= customer.notes %></p>
  </div>
</div>
</div>

app/views/customers/alphabetized.html.erb
<h1>Customers ordered by name</h1>

<%= link_to 'All Customers', customers_path %>
<%= link_to 'Customers with Missing Email', missing_email_customers_path %>

<div class = "customers-container">   
<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>
</div>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<%= link_to 'Customers with Missing Email', missing_email_customers_path %> </br>
<%= link_to 'Customers ordered by name', alphabetized_customers_path %>

<div class = "customers-container">
<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>
<div>

app/views/customers/missing_email.html.erb
<h1>Customers that do not have an email</h1>

<%= link_to 'All Customers', customers_path %>
<%= link_to 'Customers ordered by name', alphabetized_customers_path %>

<div class = "customers-container">   
<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'customer', media: 'all' %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>